//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace learn_180522_webservice.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWareCell", ReplyAction="http://tempuri.org/IService1/GetWareCellResponse")]
        string GetWareCell(string jsonText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWareCell", ReplyAction="http://tempuri.org/IService1/GetWareCellResponse")]
        System.Threading.Tasks.Task<string> GetWareCellAsync(string jsonText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoadTasksResult", ReplyAction="http://tempuri.org/IService1/LoadTasksResultResponse")]
        string LoadTasksResult(string jsonText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoadTasksResult", ReplyAction="http://tempuri.org/IService1/LoadTasksResultResponse")]
        System.Threading.Tasks.Task<string> LoadTasksResultAsync(string jsonText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductWareCell", ReplyAction="http://tempuri.org/IService1/GetProductWareCellResponse")]
        string GetProductWareCell(string jsonText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductWareCell", ReplyAction="http://tempuri.org/IService1/GetProductWareCellResponse")]
        System.Threading.Tasks.Task<string> GetProductWareCellAsync(string jsonText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ProductLoadTasksResult", ReplyAction="http://tempuri.org/IService1/ProductLoadTasksResultResponse")]
        string ProductLoadTasksResult(string jsonText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ProductLoadTasksResult", ReplyAction="http://tempuri.org/IService1/ProductLoadTasksResultResponse")]
        System.Threading.Tasks.Task<string> ProductLoadTasksResultAsync(string jsonText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UnloadTasksResult", ReplyAction="http://tempuri.org/IService1/UnloadTasksResultResponse")]
        string UnloadTasksResult(string jsonText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UnloadTasksResult", ReplyAction="http://tempuri.org/IService1/UnloadTasksResultResponse")]
        System.Threading.Tasks.Task<string> UnloadTasksResultAsync(string jsonText);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : learn_180522_webservice.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<learn_180522_webservice.ServiceReference1.IService1>, learn_180522_webservice.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetWareCell(string jsonText) {
            return base.Channel.GetWareCell(jsonText);
        }
        
        public System.Threading.Tasks.Task<string> GetWareCellAsync(string jsonText) {
            return base.Channel.GetWareCellAsync(jsonText);
        }
        
        public string LoadTasksResult(string jsonText) {
            return base.Channel.LoadTasksResult(jsonText);
        }
        
        public System.Threading.Tasks.Task<string> LoadTasksResultAsync(string jsonText) {
            return base.Channel.LoadTasksResultAsync(jsonText);
        }
        
        public string GetProductWareCell(string jsonText) {
            return base.Channel.GetProductWareCell(jsonText);
        }
        
        public System.Threading.Tasks.Task<string> GetProductWareCellAsync(string jsonText) {
            return base.Channel.GetProductWareCellAsync(jsonText);
        }
        
        public string ProductLoadTasksResult(string jsonText) {
            return base.Channel.ProductLoadTasksResult(jsonText);
        }
        
        public System.Threading.Tasks.Task<string> ProductLoadTasksResultAsync(string jsonText) {
            return base.Channel.ProductLoadTasksResultAsync(jsonText);
        }
        
        public string UnloadTasksResult(string jsonText) {
            return base.Channel.UnloadTasksResult(jsonText);
        }
        
        public System.Threading.Tasks.Task<string> UnloadTasksResultAsync(string jsonText) {
            return base.Channel.UnloadTasksResultAsync(jsonText);
        }
    }
}
